version: '3.8'

services:
  api-gateway:
    build:
      context: .
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      CORE_SERVICE_URL: ${CORE_SERVICE_URL}
      MEDIA_SERVICE_URL: ${MEDIA_SERVICE_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - ichgram-network

networks:
  ichgram-network:
    driver: bridge
    external: true
